name: nca

networks:
  oni:
  nca:

volumes:
  db:
  oni-batches:
  oni-data-mariadb:
  oni-data-solr:
  issue-cache:
  nca-workflow:
  page-review:
  sftpgo-basedir:
  sftpgo-backups:
  sftpgo-home:
  agent-rsa:

services:
  #####
  # NCA
  #####
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nca
      - MYSQL_USER=nca
      - MYSQL_PASSWORD=nca
    volumes:
      - ./docker/mysql/:/etc/mysql/conf.d:Z
      - db:/var/lib/mysql
    networks:
      nca:

  iiif:
    image: uolibraries/rais:4-alpine
    environment:
      - RAIS_IIIFWEBPATH=/images/iiif
      - RAIS_TILECACHELEN=250
      - RAIS_TILEPATH=/var/local/workflow
    volumes:
      - nca-workflow:/var/local
    expose:
      - 12415
    networks:
      nca:

  # Web runs the binary for nca's GUI
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-app
    volumes:
      - issue-cache:/var/local/news/nca/cache
      - nca-workflow:/mnt/news
      - sftpgo-basedir:/mnt/sftpgo
      - page-review:/mnt/page-review
      - oni-batches:/mnt/batches
    environment:
      - NCA_DB_HOST=db
      - NCA_SFTP_API_URL=http://sftpgo:8080/api/v2
      - NCA_SFTP_USER=admin
      - NCA_SFTP_PASSWORD=password
      - NCA_PDF_UPLOAD_PATH=/mnt/sftpgo/data
      - NCA_PDF_PAGE_REVIEW_PATH=/mnt/page-review
      - NCA_BATCH_PRODUCTION_PATH=/mnt/batches
      - NCA_STAGING_AGENT=oni-agent:22
      - NCA_PRODUCTION_AGENT=oni-agent:22
    expose:
      - 8080
    depends_on:
      - db
      - sftpgo
      - iiif
    command: ./bin/server -c ./settings
    networks:
      nca:

  sftpgo:
    image: drakkan/sftpgo:v2.5-alpine
    volumes:
      - sftpgo-basedir:/srv/sftpgo
      - sftpgo-backups:/srv/sftpgo/backups
      - sftpgo-home:/var/lib/sftpgo
    expose:
      - 8080
      - 2022
    environment:
      - SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN=true
      - SFTPGO_DEFAULT_ADMIN_USERNAME=admin
      - SFTPGO_DEFAULT_ADMIN_PASSWORD=password
    networks:
      nca:

  workers:
    extends: web
    command: ./bin/run-jobs -c ./settings watchall
    networks:
      nca:

  proxy:
    image: nginx:1.15
    volumes:
      - ./docker/nginx/nca.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - iiif
      - sftpgo
    networks:
      nca:

  #####
  # Agent
  #####
  oni-agent:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-oni
      target: agent
    volumes:
      - oni-batches:/mnt/batches
      - agent-rsa:/etc/rsa/
    depends_on:
      - oni-db
      - oni-solr
    environment:
      - BA_BIND=:22
      - HOST_KEY_FILE=/etc/rsa/oni-agent
      - ONI_LOCATION=/opt/openoni/
      - BATCH_SOURCE=/mnt/batches
      - DB_CONNECTION=openoni:openoni@tcp(oni-db:3306)/openoni
    expose:
      - 22
    networks:
      oni:
      nca:

  #####
  # Open ONI
  #####
  oni-db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=openoni
      - MYSQL_USER=openoni
      - MYSQL_PASSWORD=openoni
    volumes:
      - ./repos/open-oni/conf/mysql/:/etc/mysql/conf.d:Z
      - oni-data-mariadb:/var/lib/mysql
    networks:
      oni:
        aliases:
          - rdbms

  oni-solr:
    image: solr:8-slim
    volumes:
      - oni-data-solr:/var/solr
    command:
      - solr-precreate
      - openoni
    networks:
      oni:
        aliases:
          - solr

  oni-iiif:
    image: uolibraries/rais:4-alpine
    environment:
      - RAIS_IIIFWEBPATH=/images/iiif
      - RAIS_TILECACHELEN=250
      - RAIS_TILEPATH=/mnt/batches
    volumes:
      - oni-batches:/mnt/batches
    networks:
      oni:
        aliases:
          - rais

  oni-web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-oni
      target: oni
    volumes:
      - oni-batches:/mnt/batches
    depends_on:
      - oni-db
      - oni-solr
      - oni-iiif
    environment:
      - APACHE_LOG_LEVEL=warn
      - ONI_DB_HOST=rdbms
      - ONI_DB_PORT=3306
      - ONI_DB_NAME=openoni
      - ONI_DB_USER=openoni
      - ONI_DB_PASSWORD=openoni
      - ONI_DEBUG=1
      - ONI_HSTS_SECONDS=0
      - ONI_LOG_LEVEL=INFO
      - ONI_SECRET_KEY=openoni
      - ONI_SOLR_URL=http://solr:8983
    networks:
      oni:
