# This is primarily for development simplicity and as a recipe for proper stack
# setup, as opposed to a good production setup.  Care has been taken to make it
# a solid default, but this isn't how we use the stack in production, so
# consider this a guideline more than anything else.
version: '2'

volumes:
  db:
  issue-cache:
  sftpgo-backups:
  sftpgo-home:

services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nca
      - MYSQL_USER=nca
      - MYSQL_PASSWORD=nca
    volumes:
      - ./docker/mysql/:/etc/mysql/conf.d:Z
      - db:/var/lib/mysql

  iiif:
    image: uolibraries/rais:4-alpine
    environment:
      - RAIS_IIIFBASEURL=$APP_URL
      - RAIS_IIIFWEBPATH=/images/iiif
      - RAIS_TILECACHELEN=250
    volumes:
      - /mnt/news/workflow:/var/local/images:z
    expose:
      - 12415

  # Web runs the binary for nca's GUI
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-app
    volumes: &ncavols
      - /mnt/news:/mnt/news:z
      - issue-cache:/var/local/news/nca/cache
    environment: &ncaenv
      - NCA_WEBROOT=$APP_URL
      - NCA_DB_HOST=db
      # The redundancy here ensures we get a warning if $NCA_NEWS_WEBROOT isn't set
      - NCA_NEWS_WEBROOT=$NCA_NEWS_WEBROOT
      - NCA_IIIF_BASE_URL=$APP_URL/images/iiif
    expose:
      - 8080
    depends_on:
      - db
      - sftpgo
      - iiif
    command: ./bin/server -c ./settings

  sftpgo:
    image: drakkan/sftpgo:v2.0-alpine
    volumes:
      - /mnt/news/sftp:/srv/sftpgo/data:z
      - sftpgo-backups:/srv/sftpgo/backups
      - sftpgo-home:/var/lib/sftpgo
    expose:
      - 8080
      - 2022

  workers:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-app
    volumes: *ncavols
    environment: *ncaenv
    depends_on:
      - db
    command: ./bin/run-jobs -c ./settings watchall

  proxy:
    image: nginx:1.15
    volumes:
      - ./docker/nginx/nca.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - iiif
      - sftpgo
