###
# Open ONI
###

FROM ubuntu:focal AS oni

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
  apache2 \
  ca-certificates \
  gcc \
  git \
  libmysqlclient-dev \
  libssl-dev \
  libxml2-dev \
  libxslt-dev \
  libjpeg-dev \
  mysql-client \
  curl \
  rsync \
  python3-dev \
  python3-venv && \
  apt-get -y install --no-install-recommends libapache2-mod-wsgi-py3

# Force apache error logs to stderr
RUN ln -sf /proc/self/fd/1 /var/log/apache2/error.log

RUN a2enmod cache cache_disk expires rewrite proxy_http ssl
RUN mkdir -p /var/cache/httpd/mod_disk_cache
RUN chown -R www-data:www-data /var/cache/httpd
RUN a2dissite 000-default.conf

RUN rm /bin/sh && ln -s /bin/bash /bin/sh
WORKDIR /opt/openoni
RUN git clone https://github.com/open-oni/open-oni.git -b v1.1.1 --depth 1 .

RUN cp docker/entrypoint.sh /
RUN chmod u+x /entrypoint.sh

# Make the pip install happen in the image so the initial container startup is faster
RUN cp ./docker/pip-install.sh /
RUN chmod +x /pip-install.sh
RUN . ./docker/_startup_lib.sh && verify_config

# This should get into core ONI - without it, docker can't properly end the
# process and waits 10s to shut down the container
RUN sed -i 's|^/startup.sh$|exec /startup.sh|' /entrypoint.sh

# Uncomment this if you need Oregon's real MARC record list in order to load titles
#RUN echo "MARC_RETRIEVAL_URLFORMAT = 'https://oregonnews.uoregon.edu/lccn/%s/marc.xml'" >> onisite/settings_local.py

EXPOSE 80
ENTRYPOINT /entrypoint.sh


###
# ONI Agent "build box"
###

FROM golang:1 AS agent-build
WORKDIR /app
RUN git clone https://github.com/open-oni/oni-agent.git -b v1.4.0 --depth 1 .
RUN make


###
# ONI Agent has to have the full ONI stack to run management commands. The only
# change is copying in the binary and setting up the entrypoint.
###

FROM oni AS agent
COPY --from=agent-build /app/bin/agent /usr/local/bin/agent
ENTRYPOINT ["/usr/local/bin/agent"]
EXPOSE 22
