# I'd love to stick with Fedora 27 for all the things, but httpd won't install
# inside Docker, so this is what we get
FROM ubuntu:16.04
MAINTAINER Jeremy Echols <jechols@uoregon.edu>

RUN apt-get update -y
RUN apt-get install -y apache2 ca-certificates

# PHP dependencies - kill this when we're fully migrated from the legacy app!
RUN apt-get install -y php libapache2-mod-php php-mcrypt php-mysql

# Legacy app install dependencies - kill this when we're fully migrated from the legacy app!
RUN apt-get install -y curl zip unzip git

RUN a2enmod cache cache_disk expires rewrite proxy_http headers
ADD apache/nca.conf /etc/apache2/sites-available/nca.conf
RUN a2dissite 000-default.conf
RUN a2ensite nca.conf
RUN mkdir -p /var/lock/apache2
RUN mkdir -p /var/run/apache2

# Legacy app install - kill this when we're fully migrated from the legacy app!
RUN git clone https://github.com/uoregon-libraries/pdf-to-chronam-admin.git /usr/local/pdf-to-chronam-admin
WORKDIR /usr/local/pdf-to-chronam-admin
RUN curl https://raw.githubusercontent.com/composer/getcomposer.org/c1ad3667731e9c5c1a21e5835c7e6a7eedc2e1fe/web/installer -s | php -- --quiet
RUN ./composer.phar install
RUN cp -r ./src /var/www/html/nca-legacy
RUN cp -r ./vendor /var/www/html/nca-legacy/vendor
RUN cp -r ./templates /var/www/html/nca-legacy/templates
RUN cp ./src/includes/config-example.php /var/www/html/nca-legacy/includes/config.php

# Force apache error logs to stderr
RUN ln -sf /proc/self/fd/1 /var/log/apache2/error.log

EXPOSE 80
COPY apache/httpd-foreground /usr/local/bin/httpd-foreground
CMD ["/usr/local/bin/httpd-foreground"]
