FROM golang:1-alpine AS build
WORKDIR /app
RUN apk add git make
RUN git clone https://github.com/open-oni/oni-agent.git /app
RUN go mod download
RUN make
WORKDIR /app2
COPY scripts/fake-oni-manager.go /app2
RUN go build -o manage.py fake-oni-manager.go

FROM alpine AS service
WORKDIR /fakeoni
RUN mkdir -p /fakeoni/data/batches
COPY --from=build /app2/manage.py /fakeoni/manage.py
COPY --from=build /app/bin/agent /usr/local/bin/agent
ENTRYPOINT ["/usr/local/bin/agent"]
EXPOSE 22
