#!/usr/bin/env bash
MAX_TRIES=15
TRIES=0
while true; do
  mysql -uroot -hdb -p123456 -e 'ALTER DATABASE nca charset=utf8'
  st=$?
  if [[ $st == 0 ]]; then
    exit 0
  fi

  let TRIES++
  if [[ $TRIES == $MAX_TRIES ]]; then
    echo "ERROR: Unable to connect to the database after $MAX_TRIES attempts"
    exit 2
  fi

  sleep 5
done
